//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_WebApp.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactoRequest
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string mensaje { get; set; }
        public string asunto { get; set; }
        public Nullable<bool> contactar { get; set; }
        public Nullable<bool> noticias { get; set; }
        public Nullable<byte> prioridad { get; set; }
    }
}
