//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_WebApp.API.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frutas
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precioKg { get; set; }
        public string imgUri { get; set; }
        public decimal stockKg { get; set; }
    }
}
